# settings
title: github pages site test 
description: site description test
baseurl: ""
url: "https://terryoneil.github.io"
future: true
show_excerpts: true

# build settings
markdown: kramdown
theme: minima
