# settings
name: terry o'neil
title: terry o'neil - blog 
email: terryoneil39@gmail.com
description: site description test
baseurl: ""
url: "https://terryoneil.github.io"
future: true
show_excerpts: true

# build settings
theme: minima
