site_name: Terry O'Neil
theme:
  name: material
  features:
    - content.tooltips
nav:
  - Home: index.md
  - Git for Writers: git-guide.md
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/terry-o-a0634b243/
    - icon: fontawesome/regular/envelope
      link: mailto:terryoneil39@gmail.com
watch:
  - includes